"""
Augment Smell Analysis
========================
Scans all code_smells.json files in output/{repo-name}/ directories
and generates missing smell_analysis for entries.

## Generation Logic

The script will generate smell_analysis when ANY of these conditions are met:
1. **--force flag**: Regenerate everything (overwrite existing)
2. **Missing analysis**: Entry has no smell_analysis

## Selection Logic

**Default behavior** (no --project-name):
- Only processes repos with "selected": true in repo_list.json
- Applies language filter (default: python)

**With --project-name**:
- Processes specified projects regardless of "selected" status
- User's explicit choice overrides repo_list.json settings
- Still applies language filter if specified

## Usage Examples

```bash
# Process all selected Python repos (default)
python augment_custom_rubrics.py

# Process all selected repos of any language
python augment_custom_rubrics.py --language all

# Process specific project (ignores selected status)
python augment_custom_rubrics.py --project-name click

# Preview what would be done
python augment_custom_rubrics.py --language python --dry-run

# Force regenerate everything for specific project
python augment_custom_rubrics.py --project-name flask --force
```

## Command Line Arguments

- `--output-dir OUTPUT_DIR`: Root output directory (default: output)
- `--model MODEL`: LLM model to use (default: anthropic/claude-sonnet-4-5-20250929)
- `--base-url URL`: Optional API base URL
- `--force`: Force regeneration even if analysis already exists
- `--dry-run`: Show what would be done without making changes
- `--project-name NAME`: Process specific project(s), can be specified multiple times
- `--language LANG`: Only process repos/entries with this language (python/java/go)
- `--repo-list PATH`: Path to repo_list.json (default: repo_list.json)

## Token Usage Display

The script shows detailed token usage including:
- input_tokens: New tokens sent to the model
- cache_read_tokens: Tokens read from prompt cache (cheaper)
- cache_creation_tokens: Tokens written to prompt cache
- output_tokens: Tokens generated by the model
- total_cost_usd: Estimated cost in USD
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Optional

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from claude_cli import call_llm
from smell_benchmark import (
    _parse_xml_tag,
)


def load_repo_list(repo_list_path: str = "repo_list.json") -> Dict:
    """Load repo_list.json for getting repo metadata like language."""
    if not os.path.exists(repo_list_path):
        return {}

    try:
        with open(repo_list_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def load_smell_analysis_prompt() -> str:
    """Load the smell analysis prompt template from template directory."""
    template_path = Path(__file__).parent / "template" / "smell_analysis_prompt.md"
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    with open(template_path, "r", encoding="utf-8") as f:
        return f.read()


def generate_smell_analysis_only(
    smell_type: str,
    smell_content: str,
    smell_description: str = "",
    model: str = "anthropic/claude-sonnet-4-5-20250929",
    base_url: Optional[str] = None,
) -> tuple[Optional[str], Dict]:
    """Generate smell analysis for a case via LLM.

    Returns:
        (smell_analysis, usage)
    """
    prompt_template = load_smell_analysis_prompt()

    prompt = prompt_template.format(
        smell_type=smell_type,
        smell_description=smell_description,
        smell_diff=smell_content,
    )

    result = call_llm(prompt, model=model, base_url=base_url)
    usage = result.get("usage", {})
    raw = result.get("raw", "")

    smell_analysis = _parse_xml_tag(raw, "analysis")

    if smell_analysis:
        print(f"    Generated smell analysis ({len(smell_analysis)} chars)")
    else:
        # Fallback: use raw text as analysis if XML parsing fails
        smell_analysis = raw
        print(f"    Generated smell analysis ({len(smell_analysis)} chars, XML parse failed, using raw)")

    return smell_analysis, usage


def process_code_smells_file(
    file_path: Path,
    repo_name: str,
    model: str,
    base_url: Optional[str] = None,
    force: bool = False,
    dry_run: bool = False,
    language_filter: Optional[str] = None,
    repo_metadata: Optional[Dict] = None,
) -> Dict[str, int]:
    """Process a single code_smells.json file and augment missing smell_analysis.

    Args:
        file_path: Path to code_smells.json
        repo_name: Name of the repository
        model: Model to use for generation
        base_url: Optional base URL for API
        force: Force regeneration even if analysis exists
        dry_run: Don't actually modify files
        language_filter: Only process entries matching this language
        repo_metadata: Metadata from repo_list.json (includes language, selected, etc.)

    Returns:
        Statistics dict with counts of processed/skipped/updated entries
    """
    stats = {
        "total": 0,
        "skipped_complete": 0,
        "skipped_no_smell": 0,
        "skipped_language": 0,
        "updated": 0,
        "failed": 0,
    }

    # Check repo metadata for language and selected status
    repo_language = None
    repo_selected = True  # Default to True if no metadata

    if repo_metadata:
        repo_language = repo_metadata.get("language", "python").lower()
        repo_selected = repo_metadata.get("selected", False)

        # Skip if repo is not selected in repo_list.json
        if not repo_selected:
            print(f"  Repo {repo_name} is not selected in repo_list.json, skipping")
            return stats

        # Skip if language filter is specified and doesn't match
        if language_filter and repo_language != language_filter.lower():
            print(f"  Repo {repo_name} language ({repo_language}) doesn't match filter ({language_filter}), skipping")
            return stats

    # Load existing entries
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            entries = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"  Error loading {file_path}: {e}")
        return stats

    if not isinstance(entries, list):
        print(f"  Warning: {file_path} does not contain a list, skipping")
        return stats

    stats["total"] = len(entries)
    modified = False

    for idx, entry in enumerate(entries):
        # Skip entries without smell_content
        if not entry.get("smell_content"):
            stats["skipped_no_smell"] += 1
            continue

        # Check entry language against filter
        entry_language = entry.get("language", "").lower()

        # If language filter is specified, check entry language
        if language_filter:
            filter_lang = language_filter.lower()
            # Skip if entry language doesn't match filter
            if entry_language and entry_language != filter_lang:
                stats["skipped_language"] += 1
                continue
            # If entry has no language but repo has language, use repo language
            if not entry_language and repo_language and repo_language != filter_lang:
                stats["skipped_language"] += 1
                continue

        # Check if smell_analysis needs to be generated
        existing_analysis = entry.get("smell_analysis", "")
        needs_generation = False
        generation_reason = ""

        if force:
            needs_generation = True
            generation_reason = "forced"
        elif not existing_analysis:
            needs_generation = True
            generation_reason = "missing analysis"

        if not needs_generation:
            stats["skipped_complete"] += 1
            continue

        # Extract metadata
        smell_type = entry.get("type", "unknown")
        smell_content = entry.get("smell_content", "")
        smell_description = entry.get("description", "")
        instance_id = entry.get("instance_id", f"entry_{idx}")

        print(f"  [{idx+1}/{len(entries)}] Generating analysis for {instance_id} "
              f"(reason: {generation_reason})")

        if dry_run:
            stats["updated"] += 1
            print(f"    [DRY RUN] Would generate analysis")
            continue

        try:
            # Generate analysis only
            analysis, usage = generate_smell_analysis_only(
                smell_type=smell_type,
                smell_content=smell_content,
                smell_description=smell_description,
                model=model,
                base_url=base_url,
            )

            # Update entry with analysis
            entry["smell_analysis"] = analysis
            entry["analysis_usage"] = {**usage, "model": model}

            # Update timing_stats if it exists
            if "timing_stats" in entry and "all_candidate_attempts" in entry["timing_stats"]:
                attempts = entry["timing_stats"]["all_candidate_attempts"]
                # Find the successful attempt and update its smell_analysis
                for att in attempts:
                    if att.get("success"):
                        att["smell_analysis"] = {
                            "duration_seconds": usage.get("duration_ms", 0) / 1000.0,
                            "usage": dict(usage)
                        }
                        break

            stats["updated"] += 1
            modified = True

            # Print detailed token usage (including cache tokens)
            in_tok = usage.get("input_tokens", 0)
            cache_read = usage.get("cache_read_tokens", 0)
            cache_create = usage.get("cache_creation_tokens", 0)
            out_tok = usage.get("output_tokens", 0)
            cost = usage.get("total_cost_usd", 0.0)

            # Total input includes both regular input and cache creation
            total_in = in_tok + cache_create
            # Effective input seen by model includes cache read
            effective_in = in_tok + cache_read

            print(f"    Generated analysis")
            print(f"    Tokens: in={in_tok:,}, cache_read={cache_read:,}, cache_create={cache_create:,}, "
                  f"out={out_tok:,}")
            print(f"    Total: {total_in:,} input + {cache_read:,} cached = {effective_in:,} effective, "
                  f"cost=${cost:.4f}")

        except Exception as e:
            print(f"    Error generating analysis: {e}")
            stats["failed"] += 1
            continue

    # Save modified file
    if modified and not dry_run:
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(entries, f, indent=2, ensure_ascii=False)
            print(f"  Saved updated file: {file_path}")
        except OSError as e:
            print(f"  Error saving {file_path}: {e}")
            return stats

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Augment smell_analysis in code_smells.json files"
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Root output directory containing repo subdirectories (default: output)",
    )
    parser.add_argument(
        "--model",
        default="anthropic/claude-sonnet-4-5-20250929",
        help="Model for generating rubrics (default: anthropic/claude-sonnet-4-5-20250929)",
    )
    parser.add_argument(
        "--base-url",
        default=None,
        help="Base URL for API calls (optional)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate analysis even for entries that already have it",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without actually making changes",
    )
    parser.add_argument(
        "--project-name",
        action="append",
        dest="project_names",
        help="Only process specific project(s) (can be specified multiple times)",
    )
    parser.add_argument(
        "--language",
        default="python",
        help="Only process repos/entries with this language (default: python). Use 'all' or empty string for all languages.",
    )
    parser.add_argument(
        "--repo-list",
        default="repo_list.json",
        help="Path to repo_list.json for metadata (default: repo_list.json)",
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    if not output_dir.exists():
        print(f"Error: Output directory not found: {output_dir}")
        sys.exit(1)

    # Normalize language filter: treat 'all' or empty string as no filter
    language_filter = args.language
    if language_filter and language_filter.lower() in ("all", ""):
        language_filter = None

    # Load repo metadata from repo_list.json
    repo_list = load_repo_list(args.repo_list)
    if repo_list:
        print(f"Loaded metadata for {len(repo_list)} repos from {args.repo_list}")
    else:
        print(f"Warning: Could not load {args.repo_list}, proceeding without repo metadata")

    # Find all code_smells.json files
    code_smells_files = []

    if args.project_names:
        # Process only specified projects
        for repo_name in args.project_names:
            # Check if repo exists in repo_list
            if repo_name not in repo_list:
                print(f"Warning: Project '{repo_name}' not found in {args.repo_list}")
                continue

            repo_metadata = repo_list[repo_name]

            # When user explicitly specifies project names, ignore selected check
            # (user's explicit choice overrides repo_list.json settings)

            # Check language filter
            if language_filter:
                repo_lang = repo_metadata.get("language", "python").lower()
                if repo_lang != language_filter.lower():
                    print(f"Warning: Project '{repo_name}' language ({repo_lang}) doesn't match filter ({language_filter})")
                    continue

            # Check if code_smells.json exists
            repo_dir = output_dir / repo_name
            code_smells_path = repo_dir / "code_smells.json"
            if not code_smells_path.exists():
                print(f"Warning: code_smells.json not found for '{repo_name}' at {code_smells_path}")
                continue

            code_smells_files.append((repo_name, code_smells_path, repo_metadata))
    else:
        # Process all repos from repo_list that match criteria
        # IMPORTANT: Only process repos marked as "selected": true in repo_list.json
        for repo_name, repo_metadata in repo_list.items():
            # Check if repo is selected (this is a required filter when not using --project-name)
            if not repo_metadata.get("selected", False):
                continue

            # Check language filter
            if language_filter:
                repo_lang = repo_metadata.get("language", "python").lower()
                if repo_lang != language_filter.lower():
                    continue

            # Check if code_smells.json exists
            repo_dir = output_dir / repo_name
            code_smells_path = repo_dir / "code_smells.json"
            if not code_smells_path.exists():
                continue

            code_smells_files.append((repo_name, code_smells_path, repo_metadata))

    if not code_smells_files:
        print(f"No code_smells.json files found in {output_dir}")
        sys.exit(0)

    print(f"Found {len(code_smells_files)} code_smells.json files to process")
    if args.dry_run:
        print("[DRY RUN MODE - no changes will be made]")
    print()

    # Process each file
    total_stats = {
        "total": 0,
        "skipped_complete": 0,
        "skipped_no_smell": 0,
        "skipped_language": 0,
        "updated": 0,
        "failed": 0,
    }

    for repo_name, file_path, repo_metadata in code_smells_files:
        print(f"Processing {repo_name}:")
        stats = process_code_smells_file(
            file_path=file_path,
            repo_name=repo_name,
            model=args.model,
            base_url=args.base_url,
            force=args.force,
            dry_run=args.dry_run,
            language_filter=language_filter,
            repo_metadata=repo_metadata,
        )

        # Accumulate stats
        for key in total_stats:
            total_stats[key] += stats[key]

        # Print per-file summary
        print(f"  Summary: {stats['total']} total, "
              f"{stats['updated']} updated, "
              f"{stats['skipped_complete']} skipped (complete), "
              f"{stats['skipped_no_smell']} skipped (no smell), "
              f"{stats['skipped_language']} skipped (language), "
              f"{stats['failed']} failed")
        print()

    # Print overall summary
    print("="*60)
    print("Overall Summary:")
    print(f"  Total entries: {total_stats['total']}")
    print(f"  Updated: {total_stats['updated']}")
    print(f"  Skipped (already complete): {total_stats['skipped_complete']}")
    print(f"  Skipped (no smell content): {total_stats['skipped_no_smell']}")
    print(f"  Skipped (language mismatch): {total_stats['skipped_language']}")
    print(f"  Failed: {total_stats['failed']}")

    if args.dry_run:
        print("\n[DRY RUN COMPLETED - no actual changes were made]")


if __name__ == "__main__":
    main()
